export const HUBSPOT_INDUSTRIES = [
    { value: "", label: "- Select Industry -" },
    { value: "ACCOUNTING", label: "Accounting" },
    { value: "AIRLINES_AVIATION", label: "Airlines/Aviation" },
    { value: "ANIMATION", label: "Animation" },
    { value: "APPAREL_FASHION", label: "Apparel & Fashion" },
    { value: "AUTOMOTIVE", label: "Automotive" },
    { value: "BANKING", label: "Banking" },
    { value: "BIOTECHNOLOGY", label: "Biotechnology" },
    { value: "BUSINESS_SUPPLIES_AND_EQUIPMENT", label: "Business Supplies & Equipment" },
    { value: "COMPUTER_GAMES", label: "Computer Games" },
    { value: "COMPUTER_HARDWARE", label: "Computer Hardware" },
    { value: "COMPUTER_NETWORKING", label: "Computer Networking" },
    { value: "COMPUTER_SOFTWARE", label: "Computer Software/Engineering" },
    { value: "CONSTRUCTION", label: "Construction" },
    { value: "CONSUMER_ELECTRONICS", label: "Consumer Electronics" },
    { value: "CONSUMER_GOODS", label: "Consumer Goods" },
    { value: "CONSUMER_SERVICES", label: "Consumer Services" },
    { value: "EDUCATION_MANAGEMENT", label: "Education Management" },
    { value: "E_LEARNING", label: "E-Learning" },
    { value: "ENTERTAINMENT", label: "Entertainment" },
    { value: "FINANCIAL_SERVICES", label: "Financial Services" },
    { value: "FOOD_BEVERAGES", label: "Food & Beverages" },
    { value: "GOVERNMENT_ADMINISTRATION", label: "Government Administration" },
    { value: "HEALTH_WELLNESS_AND_FITNESS", label: "Health, Wellness & Fitness" },
    { value: "HIGHER_EDUCATION", label: "Higher Education" },
    { value: "HOSPITAL_HEALTH_CARE", label: "Hospital & Health Care" },
    { value: "HOSPITALITY", label: "Hospitality" },
    { value: "HUMAN_RESOURCES", label: "Human Resources" },
    { value: "INFORMATION_SERVICES", label: "Information Services" },
    { value: "INFORMATION_TECHNOLOGY_AND_SERVICES", label: "Information Technology & Services" },
    { value: "INSURANCE", label: "Insurance" },
    { value: "INTERNET", label: "Internet" },
    { value: "LEGAL_SERVICES", label: "Legal Services" },
    { value: "LOGISTICS_AND_SUPPLY_CHAIN", label: "Logistics & Supply Chain" },
    { value: "MANAGEMENT_CONSULTING", label: "Management Consulting" },
    { value: "MARKETING_AND_ADVERTISING", label: "Marketing & Advertising" },
    { value: "MECHANICAL_OR_INDUSTRIAL_ENGINEERING", label: "Mechanical/Industrial Engineering" },
    { value: "MEDIA_PRODUCTION", label: "Media Production" },
    { value: "MEDICAL_DEVICES", label: "Medical Devices" },
    { value: "MEDICAL_PRACTICE", label: "Medical Practice" },
    { value: "NON_PROFIT_ORGANIZATION_MANAGEMENT", label: "Non-Profit Organization Management" },
    { value: "OIL_ENERGY", label: "Oil & Energy" },
    { value: "ONLINE_MEDIA", label: "Online Media" },
    { value: "PHARMACEUTICALS", label: "Pharmaceuticals" },
    { value: "PROFESSIONAL_TRAINING_COACHING", label: "Professional Training & Coaching" },
    { value: "REAL_ESTATE", label: "Real Estate" },
    { value: "RESTAURANTS", label: "Restaurants" },
    { value: "RETAIL", label: "Retail" },
    { value: "SOFTWARE", label: "Software" },
    { value: "STAFFING_AND_RECRUITING", label: "Staffing & Recruiting" },
    { value: "TELECOMMUNICATIONS", label: "Telecommunications" },
    { value: "UTILITIES", label: "Utilities" },
    { value: "VENTURE_CAPITAL_PRIVATE_EQUITY", label: "Venture Capital & Private Equity" },
    { value: "WAREHOUSING", label: "Warehousing" },
    { value: "WHOLESALE", label: "Wholesale" }
];
